//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.26 at 05:18:01 PM WEST 
//


package br.com.klayrocha;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.com.klayrocha package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.com.klayrocha
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomerDetailRequisicao }
     * 
     */
    public GetCustomerDetailRequisicao createGetCustomerDetailRequisicao() {
        return new GetCustomerDetailRequisicao();
    }

    /**
     * Create an instance of {@link GetCustomerDetailResposta }
     * 
     */
    public GetCustomerDetailResposta createGetCustomerDetailResposta() {
        return new GetCustomerDetailResposta();
    }

    /**
     * Create an instance of {@link CustomerDetail }
     * 
     */
    public CustomerDetail createCustomerDetail() {
        return new CustomerDetail();
    }

    /**
     * Create an instance of {@link GetAllCustomerDetailResposta }
     * 
     */
    public GetAllCustomerDetailResposta createGetAllCustomerDetailResposta() {
        return new GetAllCustomerDetailResposta();
    }

    /**
     * Create an instance of {@link DeleteCustomerResposta }
     * 
     */
    public DeleteCustomerResposta createDeleteCustomerResposta() {
        return new DeleteCustomerResposta();
    }

    /**
     * Create an instance of {@link DeleteCustomerRequisicao }
     * 
     */
    public DeleteCustomerRequisicao createDeleteCustomerRequisicao() {
        return new DeleteCustomerRequisicao();
    }

    /**
     * Create an instance of {@link GetAllCustomerDetailRequisicao }
     * 
     */
    public GetAllCustomerDetailRequisicao createGetAllCustomerDetailRequisicao() {
        return new GetAllCustomerDetailRequisicao();
    }

    /**
     * Create an instance of {@link InsertCustomerRequisicao }
     * 
     */
    public InsertCustomerRequisicao createInsertCustomerRequisicao() {
        return new InsertCustomerRequisicao();
    }

    /**
     * Create an instance of {@link InsertCustomerResposta }
     * 
     */
    public InsertCustomerResposta createInsertCustomerResposta() {
        return new InsertCustomerResposta();
    }

}
